// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/26/2024, 6:32:04 PM
const configMerger = require("/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/plugins/**/*.{js,ts,mjs}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/composables/**/*.{js,ts,mjs}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/utils/**/*.{js,ts,mjs}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/remy.cnl/remy/Personnal-Projects/DoYouLoveMe/app.config.{js,ts,mjs}"] } }));

module.exports = config
